#! /bin/sh
### BEGIN INIT INFO
# Provides:          skeleton
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.
#                    copy this file to /etc/init.d/btsync
### END INIT INFO


# Start or Stop BT Sync
case "$1" in
  start)
        btsync --config /home/pi/.btsync.conf
    ;;
  stop)
        pkill btsync
    ;;
  *)
    echo "Usage: /etc/init.d/btsync {start|stop}"
    exit 1
    ;;
esac

exit 0
