#!/bin/bash
### init.d file for centos. start() function is working.
### add this to bootup using chkconfig btsync on
# chkconfig: 35 85 15
BIN='/root/btsync/btsync'
CONF='/root/btsync/btsync_api.conf'
PID='/var/run/btsync/btsync.pid'
PIDMATCH=true
SERVICE=$(basename $0)

test $(id -u) -ne 0 && echo "This is for root." >&2 && exit 1

main(){
	case $1 in
	  start)
	    if begin
	    then
	      echo "$SERVICE successfully started"
	      exit 0
	    else
	      echo "Error starting $SERVICE." >&2
	      exit 1
	    fi
	  ;;
	  stop)
	    if end
	    then
	      echo "$SERVICE successfully stopped"
	      exit 0
	    else
	      echo "Error stopping $SERVICE" >&2
	      exit 1
	    fi
	  ;;
	  status)
	    query
	    exit $?
	  ;;
	  *)
	    printUsage
	    exit 1
	  ;;
	esac
}

running(){
	test ! -f $PID && return 1
	listen=$(netstat -tnlp | grep btsync | awk '{print $NF}' | cut -d'/' -f1)
	last=$(cat $PID)
	test -z $listen && return 1
	if [[ $listen -ne $last ]]
	then
	  echo "Warning: PID of listening instance does not match PID in $PID" >&2
	  PIDMATCH=false
	  return 0
	else
	  return 0
	fi
}

begin(){
	if running
	then
	  echo "$SERVICE is already running." >&2
	  return 1
	else
	  $BIN --config $CONF
	fi
}

end(){
	if running
	then
	  if ! $PIDMATCH
	  then
	    echo "Error: Failed to stop $SERVICE: PID in $PID does not match PID of listening instance" >&2
	    return 1
	  fi
	  kill -15 $(cat $PID)
	  xstat=$?
	  rm $PID
	  return $xstat
	else
	  echo "$SERVICE is not running."
	  return 1
	fi
}

query(){
	if running
	then
	  echo "$SERVICE is running"
	  return 0
	else
	  echo "$SERVICE is stopped"
	  return 0
	fi
}

printUsage(){
	echo "Usage: $0 [start|stop|status]"
}

main $*
